# Generated by Django 5.1.1 on 2024-09-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='street',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='zip_code',
        ),
    ]
